# Generated by Django 3.2.8 on 2021-10-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0007_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
