# Generated by Django 3.2.8 on 2021-10-28 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0009_auto_20211028_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
