# Generated by Django 3.2.8 on 2021-10-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0016_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
