# Generated by Django 3.2.8 on 2021-10-22 19:55

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepicture',
            field=sorl.thumbnail.fields.ImageField(upload_to='profiles'),
        ),
    ]
